name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - name: Cache node modules
        uses: actions/cache@v1.1.0
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm run affected:test
      - name: Lint
        run: npm run affected:lint
      - name: e2e
        run: npm run affected:e2e
      - name: build
        run: npm run affected:build

        env:
          CI: true
